theme: minima

title: "https://El Heraldo del Viejo Mundo"
description: "Noticias, rumores y estrategia de Warhammer: The Old World en espa√±ol."

url: "https://www.elheraldodelviejomundo.com"
baseurl: ""

paginate: 30
excerpt_separator: "<!-- fin-excerpt -->"
paginate_path: "/page:num"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true



collections:
  videos:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      seo:
        type: BlogPosting
