theme: minima

title: "El Heraldo del Viejo Mundo"
description: "Noticias, rumores y estrategia de Warhammer: The Old World en espaÃ±ol."

url: "www.elheraldodelviejomundo.com"
baseurl: ""

paginate: 30
paginate_path: "/page:num"
plugins:
  - jekyll-paginate
